// Sample data - in a real app, this would come from an API


// Define types for our storage facilities
interface StorageFacility {
    id: number
    name: string
    type: "warehouse" | "cold-storage"
    location: string
    capacity: number
    contact: string
    facilities: string[]
    price: string
    available: boolean
}

const storageData = [

    {
        "id": 1,
        "district": "Ambala",
        "name": "S.R. Cold Store",
        "owner": "Sanjeev Kumar, Shishpal, Shiyaram, Manish Kumar Vill-Sirashgarh (Ambala)",
        "contact": "",
        "capacity": 4500,
        "year": "1998 & 2001",
        "produce": "Potato Banana",
        "scheme": "NHM",
        "remarks": "Extension of existing Cold Store"
    },
    {
        "id": 2,
        "district": "Ambala",
        "name": "Shri Shivam Cold Store",
        "owner": "S Sushilakumar, Vill-Mullana",
        "contact": "9896374128",
        "capacity": 1500,
        "year": "1997",
        "produce": "Potato",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 3,
        "district": "Ambala",
        "name": "Markanda Cold Store & ICE Factory",
        "owner": "Lekhtraj Heralal, VPO- Saha",
        "contact": "9991587882",
        "capacity": 3550,
        "year": "1995 & 2001",
        "produce": "Potato",
        "scheme": "NHM",
        "remarks": "Extension of existing Cold Store"
    },
    {
        "id": 4,
        "district": "Ambala",
        "name": "Kamdhanu Cold Store",
        "owner": "ParsotumDass, Vill- Tepla, Saha",
        "contact": "9416026199",
        "capacity": 2250,
        "year": "1998",
        "produce": "Potato",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 5,
        "district": "Ambala",
        "name": "S.P Cold Store & ICE factory",
        "owner": "Harish Kumar Rakesh Mohan HarminderGoel, Vill-Rukree (Dosarka), Ambala",
        "contact": "9416375948",
        "capacity": 2000,
        "year": "1991",
        "produce": "Potato",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 6,
        "district": "Ambala",
        "name": "Milap Cold Store",
        "owner": "Anil Ahuja, VPO-Shehzadpur",
        "contact": "9355211994",
        "capacity": 2000,
        "year": "1984 & 1984",
        "produce": "Potato",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 7,
        "district": "Ambala",
        "name": "Janta Cold Store",
        "owner": "Mohan Lal, VPO-Naraingarh",
        "contact": "1734284072, 9729541488",
        "capacity": 2500,
        "year": "1979 & 1979",
        "produce": "Potato",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 8,
        "district": "Ambala",
        "name": "Shivalik Cold Store",
        "owner": "Ajit Dang, VPO-Naraingarh",
        "contact": "",
        "capacity": 2500,
        "year": "1975 & 1976",
        "produce": "Potato & Onion",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 9,
        "district": "Ambala",
        "name": "Shivalik Cold Storage",
        "owner": "",
        "contact": "01734284101",
        "capacity": 2912,
        "year": "2015-16",
        "produce": "",
        "scheme": "NHM",
        "remarks": "incomplete"
    },
    {
        "id": 10,
        "district": "Ambala",
        "name": "Shree Ganesh Cold Store",
        "owner": "Gulshan Dang, VPO-Naraingarh",
        "contact": "01734263362, 9466409017",
        "capacity": 2200,
        "year": "1995 & 1996",
        "produce": "Potato",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 11,
        "district": "Ambala",
        "name": "HarMilap Cold Store",
        "owner": "Vijay Dang, VPO-Naraingarh",
        "contact": "01734263151, 9416009419",
        "capacity": 2300,
        "year": "2000 & 2001",
        "produce": "Potato",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 12,
        "district": "Ambala",
        "name": "Khosla Cold Store",
        "owner": "Pardeep Kumar S/o VedparkshKhosla, Hisar Road, Near Saranga Village",
        "contact": "9896604887",
        "capacity": 4000,
        "year": "",
        "produce": "Potato & Onion",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 13,
        "district": "Ambala",
        "name": "Shri Shankar Puri Cold Store",
        "owner": "Tirathram, Industrial Development Area, Near Motor Market, A/City",
        "contact": "9991120049",
        "capacity": 1500,
        "year": "1989 & 1990",
        "produce": "Potato & Fruits",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 14,
        "district": "Ambala",
        "name": "Dhillon Cold Store",
        "owner": "Rajaji, G.T. Road, Near Vill. Sahapur",
        "contact": "9896182800",
        "capacity": 2250,
        "year": "1979",
        "produce": "Potato",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 15,
        "district": "Ambala",
        "name": "M/s Markanda Cold Storage, Saha",
        "owner": "Sh. Sukdev Kumar Chauhan S/o Sh. Munshi Singh, VPO. Badhauli, The-Naraingarh, Distt-Ambala",
        "contact": "9416037377",
        "capacity": 6500,
        "year": "",
        "produce": "Fruit",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 16,
        "district": "Ambala",
        "name": "Shri Ganesh Cold Storage",
        "owner": "Village Dehar, PO Ambli, Tehsil Naraingarh",
        "contact": "",
        "capacity": 1650,
        "year": "2016-17",
        "produce": "",
        "scheme": "NHM",
        "remarks": "incomplete"
    },
    {
        "id": 17,
        "district": "Bhiwani",
        "name": "Sh. Surender Cold Store, Plot No. 25, Sector-26, Industrial Area, Bhiwani",
        "owner": "Samunder Singh S/o Sh. Abhey Ram & etc.",
        "contact": "9813248737",
        "capacity": 1450,
        "year": "2005",
        "produce": "Banana, Apple, Eggs, Grapes, Citrus",
        "scheme": "NHB, Scheme",
        "remarks": ""
    },
    {
        "id": 18,
        "district": "Bhiwani",
        "name": "Hari Om Cold Store & Allied Industries",
        "owner": "Plot No. 26, Sector-21, Industrial Area, Bhiwani",
        "contact": "",
        "capacity": 1496,
        "year": "2016-17",
        "produce": "",
        "scheme": "NHM",
        "remarks": "incomplete"
    },
    {
        "id": 19,
        "district": "Faridabad",
        "name": "Market Committee, DabuaSabji Mandi, Faridabad",
        "owner": "Market Committee, DabuaSabji Mandi, Faridabad",
        "contact": "",
        "capacity": 130,
        "year": "2014-15",
        "produce": "Fruit, vegetable",
        "scheme": "By Market Committee, Faridabad",
        "remarks": "Under Construction"
    },
    {
        "id": 20,
        "district": "Fatehabad",
        "name": "M/s Kissan Cold Store, Opp. Azad Petrol Pump, Fatehabad",
        "owner": "Sh. Mahender Singh",
        "contact": "",
        "capacity": 12,
        "year": "1998",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 21,
        "district": "Fatehabad",
        "name": "M/s Paryag cold Storage, Hissar Road, Fatehabad",
        "owner": "Sh. Naresh Kumar",
        "contact": "",
        "capacity": 12,
        "year": "1998",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 22,
        "district": "Fatehabad",
        "name": "M/s Divya Cold Storage, G.T. Road Hissar Road Fatehabad",
        "owner": "Sh. Arjun Mehta",
        "contact": "",
        "capacity": 8,
        "year": "2004",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 23,
        "district": "Fatehabad",
        "name": "M/s KapilKalash Store, Fatehabad",
        "owner": "Sh. Kapil Kumar",
        "contact": "",
        "capacity": 50,
        "year": "2005",
        "produce": "Banana",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 24,
        "district": "Fatehabad",
        "name": "M/s Guru Kirpa Store, Fatehabad",
        "owner": "Sh. Subhash",
        "contact": "",
        "capacity": 50,
        "year": "2006",
        "produce": "Banana",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 25,
        "district": "Fatehabad",
        "name": "M/s New Sat Guru Cold Store, Fatehabad",
        "owner": "Sh. Deepak",
        "contact": "",
        "capacity": 40,
        "year": "2005",
        "produce": "Banana",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 26,
        "district": "Fatehabad",
        "name": "M/s Mat Cold Store, Chandigarh Road, Tohana",
        "owner": "Sh. Satnam Dara",
        "contact": "",
        "capacity": 15,
        "year": "1995",
        "produce": "Potato, Fruit",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 27,
        "district": "Fatehabad",
        "name": "M/s Seti Cold Store, Tohana",
        "owner": "Sh. HimansuSeti",
        "contact": "",
        "capacity": 20,
        "year": "1999",
        "produce": "Potato, Fruit",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 28,
        "district": "Fatehabad",
        "name": "M/s Sindhu Cold Store, Tohana",
        "owner": "Sh. Surender",
        "contact": "",
        "capacity": 7.5,
        "year": "1985",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 29,
        "district": "Fatehabad",
        "name": "M/s Badiyal Cold Store, Jakhal",
        "owner": "Sh. NarenderBadiyal",
        "contact": "",
        "capacity": 12.5,
        "year": "1999",
        "produce": "Potato, Fruit",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 30,
        "district": "Gurgaon",
        "name": "NHM Cold Store at Grain Market,Gurgaon",
        "owner": "Market Committee,Gurgaon",
        "contact": "09468118037",
        "capacity": 500,
        "year": "",
        "produce": "Potato, Tomato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 31,
        "district": "Hisar",
        "name": "Sindhu Cold Store, Subzimandi, Hisar",
        "owner": "Baljeet Sindhu",
        "contact": "9416043856",
        "capacity": 60,
        "year": "2002-03",
        "produce": "Banana & Citrus",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 32,
        "district": "Hisar",
        "name": "Cold Store, New Veg. Market",
        "owner": "Secretary, Marketing Board, Hisar",
        "contact": "01662-275045",
        "capacity": 25,
        "year": "2012-13",
        "produce": "",
        "scheme": "NHM",
        "remarks": "Work complete but not operation"
    },
    {
        "id": 33,
        "district": "Jind",
        "name": "Aditi Cold Storage",
        "owner": "Ajay Kumar, Near Subji Mandi, Jind",
        "contact": "9416190486",
        "capacity": 1800,
        "year": "",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 34,
        "district": "Jind",
        "name": "Shiv Shakti Cold Storage",
        "owner": "Satish Kumar, Near Subji Mandi, Jind",
        "contact": "9255458300",
        "capacity": 1200,
        "year": "",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 35,
        "district": "Jind",
        "name": "Laxmi Cold Storage, Jind",
        "owner": "Kiran Kumar, Jind",
        "contact": "",
        "capacity": 0,
        "year": "",
        "produce": "",
        "scheme": "",
        "remarks": "Not in Working Position Since 2000"
    },
    {
        "id": 36,
        "district": "Jind",
        "name": "Guru Nanak Ice & Cold Storage, Jind",
        "owner": "Raj Kumar, Jind",
        "contact": "",
        "capacity": 0,
        "year": "",
        "produce": "",
        "scheme": "",
        "remarks": "Not in Working Position Since 1995"
    },
    {
        "id": 37,
        "district": "Jind",
        "name": "KhuranaJamidara Cold Storage",
        "owner": "Ram Nath, Near Subji Mandi, Jind",
        "contact": "",
        "capacity": 0,
        "year": "",
        "produce": "",
        "scheme": "",
        "remarks": "Not in Working Position Since 2002"
    },
    {
        "id": 38,
        "district": "Kaithal",
        "name": "Bharat Cold Storage Dhand Road Kaithal",
        "owner": "Sh. R. S. Gupta",
        "contact": "9416805676, 01746-320092",
        "capacity": 1500,
        "year": "1964",
        "produce": "Potato",
        "scheme": "Self-constructed",
        "remarks": ""
    },
    {
        "id": 39,
        "district": "Kaithal",
        "name": "M/s. Pawan Kumar Cold Storage",
        "owner": "Shergarh Road, Kaihal",
        "contact": "",
        "capacity": 772,
        "year": "2015-16",
        "produce": "",
        "scheme": "NHM",
        "remarks": "complete"
    },
    {
        "id": 40,
        "district": "Karnal",
        "name": "M/s A C Cold store",
        "owner": "Sh. Paramjeet SinghVill. Khera Chapra",
        "contact": "",
        "capacity": 1200,
        "year": "1988",
        "produce": "Potato",
        "scheme": "No",
        "remarks": ""
    },
    {
        "id": 41,
        "district": "Karnal",
        "name": "M/s Today Fresh",
        "owner": "Sh. Anil Gupta Vill. Chirao",
        "contact": "",
        "capacity": 3000,
        "year": "2012",
        "produce": "Empty",
        "scheme": "Horticulture Deptt. HR NHM Scheme",
        "remarks": ""
    },
    {
        "id": 42,
        "district": "Karnal",
        "name": "M/s B M Cold Store",
        "owner": "Sh. Aseem Gupta opp. sugar mill Meerut road Karnal",
        "contact": "",
        "capacity": 2500,
        "year": "1970",
        "produce": "Potato",
        "scheme": "No",
        "remarks": ""
    },
    {
        "id": 43,
        "district": "Karnal",
        "name": "M/s Shiv Shakti Cold Store",
        "owner": "Sh. Hargovind Sachdeva Sec. 3 Karnal",
        "contact": "",
        "capacity": 1300,
        "year": "1997",
        "produce": "Potato, Banana. Egg",
        "scheme": "No",
        "remarks": ""
    },
    {
        "id": 44,
        "district": "Karnal",
        "name": "M/s Guru Kirpa Cold Store",
        "owner": "Sh. Vidbhushan Chhabra Ranwar road Karnal",
        "contact": "",
        "capacity": 1200,
        "year": "2004",
        "produce": "Potato, Banana. Apple",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 45,
        "district": "Karnal",
        "name": "M/s Himalya Cold Store",
        "owner": "Sh. Virender Sharma G T Road Karnal",
        "contact": "",
        "capacity": 2000,
        "year": "1956",
        "produce": "Fruit, Banana. Apple, Grapes",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 46,
        "district": "Karnal",
        "name": "M/s Jagdish Cold Store",
        "owner": "Sh. Subash Sharma Namste Chock G T Road Karnal",
        "contact": "",
        "capacity": 2500,
        "year": "1955",
        "produce": "Closed",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 47,
        "district": "Karnal",
        "name": "M/s Maan Cold Store",
        "owner": "Sh. Randeep Singh Maan G T Road Karnal",
        "contact": "",
        "capacity": 2200,
        "year": "1975",
        "produce": "Potato, Banana",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 48,
        "district": "Karnal",
        "name": "M/s Bajaj Cold Store",
        "owner": "Sh. Mohit S/o VedParkash H No. 1473 Sect. 9 Karnal",
        "contact": "",
        "capacity": 10,
        "year": "1998",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 49,
        "district": "Karnal",
        "name": "M/s Madan Cold Store",
        "owner": "Sh. Madan Singh Near Grain Markt. Gharaunda Karnal",
        "contact": "",
        "capacity": 20,
        "year": "1986",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 50,
        "district": "Karnal",
        "name": "M/s Kishan Cold Store",
        "owner": "Sh. Sukhwant Singh S/o Angreg Singh Bisham Colony Gharaunda Karnal",
        "contact": "",
        "capacity": 20,
        "year": "1988",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 51,
        "district": "Karnal",
        "name": "M/s Haffed Cold Store",
        "owner": "Haffed G T Road Taraori",
        "contact": "",
        "capacity": 300,
        "year": "1975",
        "produce": "Potato, Egg. Chilly Dry. andCoriander Dry",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 52,
        "district": "Kurukshetra",
        "name": "Jamidara Cold Store G.T.RoadUmrTh anesar",
        "owner": "Gurdiyal Singh Malik",
        "contact": "",
        "capacity": 1750,
        "year": "1973",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 53,
        "district": "Kurukshetra",
        "name": "Umri Cold Store G.TRoadUmrThanesar",
        "owner": "Rajbir Singh",
        "contact": "",
        "capacity": 800,
        "year": "1973",
        "produce": "Potato",
        "scheme": "",
        "remarks": ""
    },
    {
        "id": 54,
        "district": "Kurukshetra",
        "name": "Atwal Cold Store Ladwa Road Thanesar",
        "owner": "Randhir Singh",
        "contact": "",
        "capacity": 1750,
        "year": "1980",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 55,
        "district": "Kurukshetra",
        "name": "Maan Cold Store Mann Ladwa Road SirsalaThanesar",
        "owner": "Phool Singh",
        "contact": "",
        "capacity": 700,
        "year": "1974",
        "produce": "Potato",
        "scheme": "NHM",
        "remarks": ""
    },
    {
        "id": 56,
        "district": "Kurukshetra",
        "name": "Hari Om Surbhi Cold Store Ladwa Road Thanesar",
        "owner": "PremParkash",
        "contact": "",
        "capacity": 1750,
        "year": "1995",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 57,
        "district": "Kurukshetra",
        "name": "Staneswar Cold Store Dhand Road Thanesar",
        "owner": "Avtar",
        "contact": "",
        "capacity": 1000,
        "year": "1985",
        "produce": "Potato/ Fruits",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 58,
        "district": "Kurukshetra",
        "name": "Shivam Fruits KDB Road Thanesar",
        "owner": "GulshanGaba",
        "contact": "",
        "capacity": 22,
        "year": "2005",
        "produce": "Potato/ Fruits",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 59,
        "district": "Kurukshetra",
        "name": "Dua Cold Store G.T. Road Shahabad",
        "owner": "Vikay Kumar Dua",
        "contact": "",
        "capacity": 4000,
        "year": "1998",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 60,
        "district": "Kurukshetra",
        "name": "Bharat Cold Store G.T Road Shahabad",
        "owner": "Yash Pal",
        "contact": "",
        "capacity": 4500,
        "year": "1975",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 61,
        "district": "Kurukshetra",
        "name": "Narang Cold Store G.T Road Shahabad",
        "owner": "LadhaPrem",
        "contact": "",
        "capacity": 4000,
        "year": "1980",
        "produce": "Potato",
        "scheme": "NHM",
        "remarks": ""
    },
    {
        "id": 62,
        "district": "Kurukshetra",
        "name": "Raj Kamal Cold Store MadanPur Road Shahabad",
        "owner": "Raj Kapoor",
        "contact": "",
        "capacity": 2100,
        "year": "1975",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 63,
        "district": "Kurukshetra",
        "name": "Mahesh Cold StoreG.T Road Shahabad",
        "owner": "R.D. Gupta",
        "contact": "",
        "capacity": 4000,
        "year": "1998",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 64,
        "district": "Kurukshetra",
        "name": "Dashmesh Cold Store Barara Road Shahabad",
        "owner": "Daya Singh Gaba",
        "contact": "",
        "capacity": 1600,
        "year": "1975",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 65,
        "district": "Kurukshetra",
        "name": "Krishna Cold Store Barara Road Shahabad",
        "owner": "Bansi Lal",
        "contact": "",
        "capacity": 5000,
        "year": "2000",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 66,
        "district": "Kurukshetra",
        "name": "AR Cold Store Barara Road Shahabad",
        "owner": "Kiran Kumar",
        "contact": "",
        "capacity": 5000,
        "year": "2001",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 67,
        "district": "Kurukshetra",
        "name": "Jai Bharat Cold Store Barara Road Shahabad",
        "owner": "KrishanLokesh",
        "contact": "",
        "capacity": 3500,
        "year": "1980",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 68,
        "district": "Kurukshetra",
        "name": "Gabha Cold Store Barara Road Shahabad",
        "owner": "Om ParkashGaba",
        "contact": "",
        "capacity": 1800,
        "year": "1980",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 69,
        "district": "Kurukshetra",
        "name": "Potato Cold Store & Pack House Govt. of Haryana Shahabad",
        "owner": "Marketing Board",
        "contact": "",
        "capacity": 2500,
        "year": "2011",
        "produce": "Potato/ Fruits",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 70,
        "district": "Kurukshetra",
        "name": "Guru Nanak Cold Store Ladwa Road Shahabad",
        "owner": "Daya Singh Gaba",
        "contact": "",
        "capacity": 2000,
        "year": "1975",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 71,
        "district": "Kurukshetra",
        "name": "Sachdeva Cold Store Ladwa Road Shahabad",
        "owner": "RaiMal Das & Son's",
        "contact": "",
        "capacity": 2250,
        "year": "1975",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 72,
        "district": "Kurukshetra",
        "name": "Neel Kanth Cold Store Ladwa Road Shahabad",
        "owner": "Papu Gandhi",
        "contact": "",
        "capacity": 2000,
        "year": "1977",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 73,
        "district": "Kurukshetra",
        "name": "Jaikissan Cold Store Ladwa Road Shahabad",
        "owner": "DilBag Rai",
        "contact": "",
        "capacity": 2000,
        "year": "1977",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 74,
        "district": "Kurukshetra",
        "name": "Jagdamba Cold Store Shahabad",
        "owner": "Narender Kumar",
        "contact": "",
        "capacity": 2000,
        "year": "1974",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 75,
        "district": "Kurukshetra",
        "name": "Zimidara Cold Store Ladwa Road Shahabad",
        "owner": "Hakkam Rai",
        "contact": "",
        "capacity": 2000,
        "year": "1976",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 76,
        "district": "Kurukshetra",
        "name": "Maansarovar Cold Store Ladwa Road Shahabad",
        "owner": "Partap Singh Kaisi",
        "contact": "",
        "capacity": 3000,
        "year": "1976",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 77,
        "district": "Kurukshetra",
        "name": "Mittal Cold Store Shahabad",
        "owner": "Panna Lal",
        "contact": "",
        "capacity": 3750,
        "year": "1980",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 78,
        "district": "Kurukshetra",
        "name": "Riki Ram Cold Store Shahabad",
        "owner": "Rikhi Ram",
        "contact": "",
        "capacity": 1750,
        "year": "1980",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 79,
        "district": "Kurukshetra",
        "name": "Kansal Cold Store Shahabad",
        "owner": "Virender Kumar",
        "contact": "",
        "capacity": 3750,
        "year": "1995",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 80,
        "district": "Kurukshetra",
        "name": "K.C. Cold Store Shahabad",
        "owner": "Anil, Parveen, Rajiv",
        "contact": "",
        "capacity": 2700,
        "year": "2000",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 81,
        "district": "Kurukshetra",
        "name": "Sindhu Cold Store Shahabad",
        "owner": "Harjot Singh",
        "contact": "",
        "capacity": 1500,
        "year": "1997",
        "produce": "Potato",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 82,
        "district": "Kurukshetra",
        "name": "DD Agro Cold Store Shahabad",
        "owner": "Harish Khuran",
        "contact": "",
        "capacity": 5000,
        "year": "2012",
        "produce": "Potato",
        "scheme": "NHM",
        "remarks": ""
    },
    {
        "id": 83,
        "district": "Kurukshetra",
        "name": "Jagdaniba Cold Store Ladwa",
        "owner": "Dev Raj",
        "contact": "",
        "capacity": 1750,
        "year": "2000",
        "produce": "Potato/ Fruits",
        "scheme": "Self",
        "remarks": ""
    },
    {
        "id": 84,
        "district": "Karukshetra",
        "name": "Indian Cold Store Ladwa",
        "owner": "YashPal Chhabra",
        "contact": "",
        "capacity": 3000,
        "year": "1977",
        "produce": "Potato/ Fruits",
        "scheme": "Self",
        "remarks": ""
    },
]
export default storageData
